### ISSUE TITLE
docs : Error tutorial docs nya banh, plis benerin banh

### ISSUE THREAD

**Issue by yogaardiansyah** [BinaryNeedle/woven#1]
### Summary
Error banh ak install pake npm, run npm

### Steps to Reproduce
1. run npm install, trus npm init
2. npm run dev 

### Expected Behavior
webnya jalan banh

### Actual Behavior
error 500

![Junior Dev Meme](https://devs.lol/uploads/2021/11/meme-dev-humor-junior-dev-looking-to-a-senior-dev-174.jpg)

**Comment by MRaihanZ** [comment]
i have change the docs. thanks for letting us know
